* Madoka Population Simulation
Models the population dynamics of witches and magical girls in Puella Magi Madoka Magica. The idea is to find out how many magical girls are necessary to maintain the cycle of magical girl -> witch -> grief seed to purify other magical girls’ soul gems.

** Top-level

Copy Rich Hickey’s ants demo. The magical girls are all agents that run a “behave” function similar to the ants in the ants demo. 

For simplicity go back to a square grid world and just copy Rich Hickey’s design with the square grid in a vector of vectors holding on to magical girl and witch values inside refs. We can numerically calculate whether they’re in each others discovery radii by just checking if any squares are shared between the two radii (which won’t be circular anymore, they’ll be square. Not rectangular, too much of a pain. Square, period). Have a lazy-seq (or something) of magical girl agents that hold their current location. As before, after +three moves+ 24ms, the magical girls will return to their home square to simulate “days”. 

So rather than the self-queuing infinitely looping function of the ant demo, maybe we actually want something else (a future, a self-queuing function on agent, a Java thread, something) that runs independently, sends off the behavior function to the magical girls, times 24ms, then sends them home by switching some value in an atom. Every time the magical girls execute a move, they check this value first and if it’s switched, they return home and stop executing. Something like:

    #+BEGIN_SRC clojure
      (def stop-hunt (atom false))
      
      (defn hunt-witches
        [location]
        (let [magical-girl (girl-at location)]
          (if @stop-hunt
            (move magical-girl (:home magical-girl)))
            ;; Go hunt witches
             (send-off *agent* hunt-witches magical-girl)))
      
       (defn do-day
         []
         (do
           (swap! stop-hunt not)
           (map
            #(send-off % hunt-witches) magical-girls)
           (Thread/sleep 24)
           (swap! stop-hunt not)
           (recur)))
           
      (let [runner (java.util.Thread. do-day)]
        (.start runner))
    #+END_SRC

The =hunt-witches= function will also contain some part where we sample a random exponential distribution with mean 12 and wait that number of milliseconds before going witch hunting again. 

Note: here are two ways to do an infinitely looping thread in Clojure:

    #+BEGIN_SRC clojure
      ;; With a Java thread set to daemon so it won't inhibit exit.
      (doto (java.util.Thread. fn-to-execute)
        (.setDaemon true)
        (.start))
      
      ;; With futures, in pure Clojure
      (defn infinite-loop
        [fn-to-execute]
        (future
          (loop []
            (fn-to-execute)
            (Thread/sleep sleep-time)
            (recur))))
      
      (infinite-loop some-fn)
      
      ;; You can stop the futures version:
      (def stop (atom false))
      
      (defn infinite-loop
        [fn-to-execute]
        (future
          (loop []
            (fn-to-execute)
            (Thread/sleep sleep-time)
            (when (not @stop)
              (recur)))))
    #+END_SRC

*** Time

+Discrete-time+. Each day, a magical girl finds a witch, finds a familiar, or finds nothing. If she finds a witch, she can defeat the witch and gain a grief seed to purify her soul gem, at the cost of magic use and possible death. If she finds a familiar, she can choose to fight it, at the cost of soul gem impurities and possible death, or to ignore it, at the cost of a small amount of soul gem impurity. If she finds nothing, her soul gem becomes a little more corrupt from the energy she expended.

Now I’m thinking I might hazard continuous time. Of course, continuous time isn’t really continuous; it’s discrete with small enough delays that it appears continuous to a human observer. 

Given that, the best thing is probably to have a “do turn” function that does an entire turn, but has no dependence at all on time. We can then run it in Quil at some framerate, and it will appear continuous,  I guess, kind of. 

Another way: rather than having a single “do turn” that does a turn for everyone, we could have something like an agent that does turns for some randomly chosen magical girls at random intervals.

The exponential distribution models the time between occurrences of events whose probability of occurring is a Poisson, so we can just say witch hunts are Poisson-distributed and have magical girls wait an amount modeled by an exponential, with mean 24ms (we’ll say 1ms = 1hr, so 24ms = 1 day). 

+Have a core.async channel that dispenses waiting times, exponentially distributed with mean 24.+ Each magical girl is a thread (of some kind—future, agent, something) that generates a number, exponentially distributed with mean 24, and waits for that many milliseconds, then goes on a witch hunt. She gets her three moves and can fight or fly from any familiars encountered during that time.

Meanwhile, the Incubators also have wait times before they can spawn a magical girl, to simulate the process of finding a suitable candidate for magical girl status.
*** Space

+Takes place on a grid. Just a big, empty grid, I think. Maybe grid spaces have “witch hospitability” values that determine how likely a witch is to take up residence there. In The Different Story there was a labyrinth with two witches inside so witches can live on the same square. Magical girls can cover the nearest twenty-square radius and return to a home square at the start of every day. Each day, the magical girl will randomly search this radius for witches. If a square is within a witch’s discovery radius, a random number is generated which serves as a discovery threshold. If the magical girl’s witch seeking power is greater than the threshold, she will discover the witch. If a square contains a witch, the magical girl finds it regardless of her witch seeking stat. Familiars are always found but do not need to be fought.+

I’m changing this from a grid with discrete squares to a continuous space. The coordinates are floating point numbers. (If this were C or Java I would probably use floats instead of doubles, since we don’t really need that precise a resolution.) The discovery radius is a literal radius that defines a circle. Magical girls also have discovery radii which are divided into five rings. 

Each turn, we check if the discovery radii of magical girls overlap with those of witches or familiars. The magical girl’s discovery radius is divided into five rings. If a witch’s discovery ring intersects the magical girl’s first ring, the witch will be discovered 100% of the time. If the witch’s discovery ring intersects at the second ring, it will be discovered 50% of the time. The third ring, 25%, the fourth ring, 14.5%, the fifth ring, 7.25%. The magical girl’s discovery stat determines the size of her discovery radius.

If the magical girl doesn’t find a witch within her discovery radius, she can choose to move to the extent of her third ring (i.e. 3/5ths of the way along her discovery radius) in any direction. +The direction is chosen randomly+. Good thing I watched Episode 2 again; the soul gem reacts to the proximity of a witch, so the magical girls can actually figure out which direction the witch is. We can use the quadtree to find a witch in the same quadrant; as an approximation, just the first one we find in the same quadrant, not actually the nearest one in total distance. But the tracking stat is still relevant, because a higher tracking stat means the discovery radius is larger, which means witches can be found from further away, and also that the inner rings will intersect the witch’s from further away, so the probability of finding a witch is higher. Magical girls can move three times before having to return home. 

I’m going to attempt to implement the discovery check with a quadtree that contains all the magical girls and witches. Witches don’t move so we won’t ever need to update the tree on their account.

Say we have a big list of all the entities (witches, magical girls, familiars—we can ignore Incubators) in the simulation right now. Then we determine the geometric midpoint of the world map along both axes. Then we need to partition the list into four areas according to which quadrant the entity falls inside. The list can be partitioned like in quicksort, only more complex since there are four regions.
*** Combat

If a magical girl discovers a witch, she must fight. The outcome of combat is determined like so:

  - Take the combat differential, magical_girl.combat - witch.combat.
  - Draw a random sample from a normal distribution with mean 0
    and standard deviation abs val of the the combat differential.
  - If the random value we drew is within one standard deviation of the
    mean on either side (i.e. in the range [-combat differential, +cd])
    or within two standard deviations in the direction of the
    differential’s sign (i.e. [-2sigma, sigma] if sigma is negative)
    then the stronger party wins.
  - If the random value is outside of this range in the direction of the combat differential’s sign, the side with the smaller combat stat wins.
  - If the combat differential is less than the magical girl’s total
    combat stat, the magical girl can choose to run away. She will do
    so according to the outcome of a random coin toss whenever this
    condition is true.
  - If the combat differential is zero, the outcome of combat is determined
    by a random coin toss.

e.g. Say we have a magical girl Sayaka with combat 50, and a witch with combat 130. The combat differential is -80. Sayaka cannot run because the difference between their combat stats is higher than her combat stat.

We take a random sample from a population which is normally distributed with mean 0 and standard deviation 80. Say we get -74.65 (rounded, drawn from a real run of Python’s random.normalvariate). Then the witch wins, because the combat differential is negative and -74.65 is within the range [-160, 80]. On the other hand, if we drew -172.77 (another real value), Sayaka wins because this value is smaller than -160.

If the magical girl wins, her soul gem is purified. If she loses, she dies. If she runs, her soul gem is corrupted.

I hope that this system will allow the stronger party to win most of the time, while also allowing the weaker party to win a fair amount of the time, with that amount increasing as the gap in power shrinks.

** Entities
*** Witches

Much simpler than magical girls, they have just a combat stat and a discoverability stat. More powerful witches are easier to find because they have larger labyrinths and create more dramatic effects (e.g. the giant storm that Walpurgisnacht caused). More powerful witches also create more familiars.

  - Combat: A real number greater than 0. 
  - Discoverability: An integer which gives the Manhattan distance
    from which a witch can be discovered by a magical girl. 
    Determined when a witch is born from the original magical girl’s
    tracking stat and the witch’s combat stat. (The logistic or sigmoid
    of the combat stat times the tracking stat.)
  - Location: The square where the witch sets up its labyrinth. 
    Whichever square a magical girl is on when her soul gem
    turns black is the square the witch starts in.

At the time of a witch’s birth, it spawns a random number of familiars between 0 and its combat stat. The familiars are randomly spread over the witch’s discovery radius. Their combat stats are 1/10th the witch’s.

*** Magical girls

  - Combat: A real number greater than 0.
  - Tracking: +A real number between 0 and 1. When a magical girl enters a witch’s discovery radius, a random number between 0 and 1 is generated. If the magical girl’s tracking stat is higher than this number, she discovers the witch. Every time a witch is defeated, the magical girl gains more tracking ability; the exact amount is determined by an exponential distribution with mean 0.05.+ Now just a real number greater than 0, which determines the size of the magical girl’s discovery radius. 
  - Soul gem: A real number between 0 and 1. The percentage of black in the magical girl’s soul gem. Increases every day by a base rate between 0.01 and 0.1 which is randomly determined at the birth of a magical girl (meant to mimic her natural resilience of personality). Combat with a familiar increases it by the base rate times 1.5; combat with a witch increases it by the base rate times 5. Defeating witches yields grief seeds, which reduce the soul gem’s corruption to zero.
  - Home square: A two-tuple for the magical girl’s home square. 
 
*** Familiars

  - Combat: A real number greater than 0.

*** Incubators

The simulation starts with some number of Incubators randomly spread across the grid. Incubators will move to a random square +at random intervals (determined by an exponential distribution)+ [Incubators have no reason to limit the number of magical girls they create; if some can’t survive, it just means more witches, so let it rip. So Incubators try to create a new magical girl every turn] and try to spawn a magical girl. They will succeed with probability p. The number of Incubators and the success probability of their attempts are parameters to the simulation. (Now changed to the mean probability of the Incubators’ success, because, really, who wants to type in a bunch of doubles, right? Better to just give up a little control and let it be somewhat random.)

Incubators are essentially ignored by the other actors in the simulation. 

  - Success: A number between 0 and 1 which indicates the likelihood of
    the Incubator succeeding at creating a magical girl. 
** Input format
   A file containing a Clojure map, which will be read in as
   EDN. Should be a map from symbols to keys (not keywords). Later we
   can also support keywords if it’s useful because I have a function
   to convert keywords to symbols.

   See config_schema.edn under resources for an example with all the
   currently allowed keys.
** Problems [updated as we go]
*** Entity problems
1. Sayaka runs away from Gertrud too much. About half the time. That makes sense since the ratio of her and Gertrud's combat differential and her combat stat is about 0.5, so about half the time the random number should be below the threshold, and about half the time it should be above. That’s about the only damn thing here that does make sense.
2. Sayaka also beats Gertrud way too much. Gertrud is stronger, but practically never wins. I would think the combat info function is somehow fucked and is getting the wrong person for stronger and weaker, except it passes all its unit tests. So I probably fucked up the system for determining the winner, probably due to my total idiocy at statistics and lack of knowledge about the normal distribution. 
3. Sayaka also wins ridiculously often against Kriemhild Gretchen; she should practically never win, ever, but she consistently wins 85% of the battles.
4. Ultimate Madoka loses to Kriemhild Gretchen way too much. She only wins about 12% of the time, with Gretchen winning about 88% of the time.

So the weaker person is way too favored by this system (unless there /is/ something fucked up in how we’re choosing the stronger and weaker combatant), and running away happens way too often. 

Chinsy solutions:
1. Just multiply the combat by 2 so the flight threshold becomes smaller.
2. Come up with a new way to do combat. Read about some probability distributions and stuff. First try just messing with the victory interval.

*** Graphical display problems
Lots of hiccuping and freezing as the number of entities on screen grows. My guess is agent overhead. 1 dot works pretty well, three sort of works, but as soon as you get to five, everything is all screwed up.

I have no idea how Rich Hickey’s ants demo deals with this. Maybe a weakness in Quil? Maybe I can get around it by using the OpenGL rendering mode?

For now going to just add witches, and then recode the whole thing to use sequential code instead of agents and proceed with Quil’s frame rate. Maybe use coarser-grained parallelism (e.g. one thread pool working across a list, like pmap or something, instead of each entity being an agent on its own.) Brian Carper had problems with agent performance too, when he tried to make every entity in his RPG game its own agent.
